spring.datasource.jdbc-url=jdbc:mysql://localhost:3307/spring_batch
spring.datasource.username=root
spring.datasource.password=1234567
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

app.datasource.jdbc-url=jdbc:mysql://localhost:3307/library
app.datasource.username=root
app.datasource.password=1234567
app.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

sendgrid.api.key=${SENDGRID_API_KEY}